openapi: 3.1.0
info:
  version: 1.0.0
  title: JetCats API
  # typo was here
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Spendy App allows to manage user's income and expense.
tags:
  - name: Transactions
    description: Operations with transactions.
  - name: Categories
    description: Information about categories.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://project-jetcats-be.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd/post.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/get-oauth-url/get.yaml
  /auth/confirm-oauth:
    post:
      $ref: ../swagger/paths/auth/confirm-oauth/post.yaml
  /user/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
  /transactions:
    post:
      $ref: ../swagger/paths/transactions/post.yaml
    get:
      $ref: '../swagger/paths/transactions/get.yaml'
  /transactions/{transactionId}:
    patch:
      $ref: '../swagger/paths/transactions/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/transactions/{id}/delete.yaml'
  /transactions/summary:
    get:
      $ref: ../swagger/paths/transactions/summary/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
